from autonomous_integration import (
    ARGUMENT_LIST,
    ARGUMENT_NAMES_AND_TYPES,
    RESPONSE_NAMES_AND_TYPES,
)

LIGHT_STATUS_DESCRIPTION = "Get light status"
LIGHT_STATUS_ARGUMENT_NAMES_AND_TYPES: ARGUMENT_NAMES_AND_TYPES = []
LIGHT_STATUS_ARGUMENTS: ARGUMENT_LIST = {}
LIGHT_STATUS_RESPONSE_NAMES_AND_TYPES: RESPONSE_NAMES_AND_TYPES = [("lighted", "bool")]


def turn_on_light()
