functions:
  - name: hello
    description: Hello world function
    argument_names_and_types:
      - name: name
        type: string
    response_names_and_types:
      - name: message
        type: string
    position: [3, 3]
robot:
  position: [0, 0]
  direction: 1.5